### PR TITLE
Add travis flake8 test and fix all the code

### PR DESCRIPTION
**Pull request by nitori**
This adds quite some changes, mostly code cleanup (pep8).

I added flake8 to `.travis.yml`, so it gets tested on every commit/pr as well.

There is probably a way to do that with `py.test`, but I haven't bothered looking to much into it.

flake8 ignores `E501`, which is the line-length thing, and `F401` which is an "imported but not used" notice.

Edit: also, `docs/` directory is ignored as well.

### CODE REVIEW

**Comment by traverseda** [comment]
I feel like I'm not getting the most out of the test cases right now. Part of that is because some fundamental things are still moving, I expect test cases to break a bunch as we make stuff better.

Is there a way to break our checks into subgroups, maybe?

**Comment by ghevcoul** [comment]
I feel like when things are still moving and there's a lot of active development is the best time to have lots of testing. It forces people to be aware of how their changes affect other parts of the code and not introduce breaking changes without fixing them everywhere. At my last job, your PRs wouldn't be merged unless they passed all tests.

Generally, if a dev breaks a test, it should be up to them to either fix their code so it matches the expected input/output or update the test to reflect their changes.

**Comment by traverseda** [comment]
At the same time, an open source project lives and dies on momentum. I see test cases as a "this code is set in stone, don't change it unless you know what you're doing" sort of flag.

Raising the requirements to do minor changes is going to kill momentum.

I think test cases should probably only be strictly enforces on essential code that other complicated systems are built on.

Our code is still pretty small, and not all that interdependent right now. It's not that far from the original teaching program, and there's only really one level of interdependence.

Honestly, I'm not that into tests myself. I'm very open to discussing policy though.

**Comment by traverseda** [comment]
I guess what I'm saying is that functions that aren't going to change between major releases _definitely_ need good test coverage. Features that can change between minor releases probably also need to be well tested, but only if that code is user/api facing. Internal implementations that change between minor releases probably don't need test cases, if that makes sense.

**Comment by mrpudn** [comment]
I agree with @ghevcoul - I think things are volatile because we're breaking things all of the time that could be otherwise backed by tests. It's eventually going to become impossible for any one person to understand the whole code base, but adding tests is a way to capture everyone's individual knowledge about how pieces of the project work. Just my thoughts :)

**Pull request merged**
