### PR TITLE
Allow controls configuration

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by traverseda** [comment]
Hey, a bunch of changes have happened to the config file in the last round or PRs, and I'm afraid there's some merge conflicts.

When they're fixed I'll be happy to merge this.

**Comment by Eijebong** [comment]
I think it's okay now :)

**Comment by Eijebong** [comment]
Well, that was quick. Thanks

**Comment by traverseda** [comment]
Yeah, it's mostly that I'm awake now ;-p

**Pull request merged**
