### PR TITLE
Support moving up/down whilst flying

### PR DESCRIPTION
**Pull request by Manishearth**
This exists in vanilla minecraft and is quite useful for exploring, instead of looking up and moving forward.

Currently only works in flying mode. It's possible to make it work in regular mode (e.g. so that one can fall faster), but it's unclear how useful that would be.

### CODE REVIEW

**Comment by Manishearth** [comment]
(Why are there two identical player.pys?)

**Comment by Eijebong** [comment]
@mrpudn forgot to delete /player.py when he moved it to /objects/player.py in #26

**Comment by Manishearth** [comment]
Cool, deleted.

**Comment by mrpudn** [comment]
Yup, it didn't get deleted when I moved it for some reason, and I was going to clean it up in #28, but this works, too :)

**Comment by traverseda** [comment]
We've got some conflicts.

**Comment by Manishearth** [comment]
Fixed

**Pull request merged**
